SELECT TOP (1000) [message_id]
      ,[session_id]
      ,[trace_id]
      ,[user_id]
      ,[agent_id]
      ,[message_type]
      ,[content]
      ,[model_name]
      ,[content_filter_results]
      ,[total_tokens]
      ,[completion_tokens]
      ,[prompt_tokens]
      ,[finish_reason]
      ,[response_time_ms]
      ,[trace_end]
      ,[tool_call_id]
      ,[tool_name]
      ,[tool_input]
      ,[tool_output]
      ,[tool_id]
  FROM [dbo].[chat_history]